[package]
name = "cargo-merge-driver"
version = "0.1.0"
authors = ["relrelb <relrelbachar@gmail.com>"]
edition = "2018"
description = "Automatically merge Cargo.lock files"

[dependencies]
clap = { version = "4", features = ["derive"] }
dirs = "5"
